### ISSUE TITLE
Autopickup not working on zero weight items

### ISSUE THREAD

**Issue by Roet718** [Kenan2000/CDDA-Structured-Kenan-Modpack#271]
weightless items like the gold coins from bl9 are ignored by autopickup for some reason. Removing the zero_weight flag allows them to be auto picked up again but then throws up multiple ignorable errors.

**Comment by Kenan2000** [comment]
@Roet718 Hmm, if this is an issue with zero_weight flag items then this is also game hardcode issue, because this flag is made in C++, try to test this with other zero_weight items from vanilla or mainlined mods then if you encounter same issue, post it so developers can try to fix it in game so that it works, BL9 is not the only mod that uses zero_weight flag, it is used in various mainlined mods so try to ask developers about it's behavior hopefully as well
