### ISSUE TITLE
0.G stable version in release

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Structured-Kenan-Modpack#319]
Can there be one?

**Comment by Kenan2000** [comment]
@linonetwo There can be CDDA Modpack stable versions releases if someone works on them but I don't work on them because this is not my work honestly. If I had been working on 0.G stable version I would have uploaded it when core game stable was released. That still does not mean that I prohibit any other person from making them including you along with @waveyl who are one of my most loyal contributors. You have my consent to make stable versions if you guys are interested in them
