### ISSUE TITLE
Barry Button rescue will not complete (Wandering Masters mod), and error messages when talking to Barry.

### ISSUE THREAD

**Issue by LuigiWhatif** [Kenan2000/CDDA-Structured-Kenan-Modpack#327]
In Wandering Masters mod the quest to rescue Barry Button will not complete.  I bring Barry right next to his brother but neither changes dialogue to finish quest.  Possibly related, two error messages appear when talking to Barry.  Images included.
![CBN_Berry1](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/60243435/1e81fae2-600e-4059-ac27-d4172d005d5e)
![CBN_Berry2](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/60243435/ea1b64d6-65c3-4bbf-afc3-8c1cb3550491)

**Comment by Kenan2000** [comment]
@LuigiWhatif Go to mod folder, open npc/Refugee center/NPC_Barry_Button.json then edit "evac_center_7" to be "evac_center_7_north" along with "bank" to be like this "bank_north" then tell me here if you get the same errors or not

**Comment by LuigiWhatif** [comment]
I made the change but I'm still getting the same issue.  Even the error messages are the exact same.

**Comment by Kenan2000** [comment]
@LuigiWhatif So I have posted an issue on official Bright Nights page on GitHub with regards to this because this is a hardcode of game issue so it can only be fixed by programmers, whereas I try to work with JSON mostly along with some scripting mostly hopefully 

So along with this, I am not sure if you play CDDA or Bright Nights so that's for you to specify, if you play with CDDA then mod that you mention is in Archived folder which means that it's abandoned, but kept there only for storage reasons for others to fix so you should not make issues about broken mods from Archived folder, which can get small fixes or updates very, very rarely, which are mostly always broken. If you find issues for me to fix then make them only about mods from other folders which include words Maintenance in them 

If you play Bright Nights then you have posted this issue in a different repository, this repository that I have made clearly literally is only for CDDA mods which I try to maintain hopefully because it's very obviously implied in it's name which is why I have called it my CDDA Modpack literally. If you want to post issues about Bright Nights mods which I try to maintain hopefully you need to post them in my Bright Nights Modpack repository if you don't mind. If you want to contact me to ask me more questions that I will try to answer hopefully then I suggest you to join my personal server link to which is in README files on GitHub of both my CDDA Modpack along with my Bright Nights Modpack both of which I try to maintain hopefully as well

**Comment by LuigiWhatif** [comment]
I was playing Bright Nights.  I had not noticed that I was commenting on the wrong modpack.  Thank you for your help.

**Comment by Kenan2000** [comment]
No problem
