### ISSUE TITLE
 Can you please help me delete it, I'm looking in the wrong place, this is an embarrassing thing.

### ISSUE THREAD

**Issue by moand-end** [Kenan2000/CDDA-Structured-Kenan-Modpack#328]
Can you please help me delete it, I'm looking in the wrong place, this is an embarrassing thing.

**Comment by Kenan2000** [comment]
No problem, nothing embarrassing. With regards to Chinese version of mod that you mention you need to message waveyl on his GitHub repository GitHub page of whom it's possible to very easily find via searching waveyl then opening his GitHub user page then finding his Chinese version of my Modpack which he maintains which is different from my original version because waveyl actually does a lot of his own custom work with him having included new mods like this mod that you have posted an issue about essentially. Yeah, nothing embarrassing, mate, no problem hopefully as well
