### ISSUE TITLE
Some mutation/cell biology specific fields ported to enchantments. 

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#341]
See DDA#72034

**Comment by Kenan2000** [comment]
@waveyl I have updated files in correspondence with 2 parts of enchantments ports pull requests so either downgrade to older commit to play right now or wait for second part of enchantment port pull request to be merged which I advise so that on this version there would be no errors associated with these mods files updates in your game version 

Now, I know that you have a keen eye for these pull requests, which I really appreciate, so if you find these types of pull requests with tons of flairs like mods that change mods files like this then please, if you can, message me on discord with these so that I can know about them to fix these more efficiently hopefully

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
