### ISSUE TITLE
BL9 unsupported format conversion on map screen

### ISSUE THREAD

**Issue by JohnHenryEton** [Kenan2000/CDDA-Structured-Kenan-Modpack#359]
https://imgur.com/a/WWdQf7a

No error message this time, but a picture of what is shown in place of name when cursor is over BL9 locations.

**Comment by Kenan2000** [comment]
That's because overmap terrains in my mod have no graphical tileset versions support, as you have said, it's not an error, so adding it is not required to do at all, it's also a hassle, so this is not even worth effort

**Comment by JohnHenryEton** [comment]
Fair enough. Thank you.

**Comment by Kenan2000** [comment]
No problem, mate

**Comment by JohnHenryEton** [comment]
This might be a shot in the dark, but would you have ideas on where to start to fix it for myself?
I've noticed that the names display properly on level -1 without this format conversion stuff.
I'd just like to be  able to tell what things are when they get marked on my map lol.
Or a workaround if you know that.

**Comment by Kenan2000** [comment]
Well, if you have read what I have posted on my discord server, what I have tweaked in description of all my modpacks for each version of this project then you probably would be reluctant to ask me this, because now maintenance of this work is abandoned, but since you still ask. Look at mods that have graphical overmap tileset support or how graphical overmap tileset support is made in general in mod tileset files. I don't even like graphical overmap tileset that much so that's basically as much as I know with regards to your question hopefully

**Comment by JohnHenryEton** [comment]
I hadn't seen those description updates nor the discord information. Good luck on your future endeavors and all that. Thank you for the starting point.

**Comment by Kenan2000** [comment]
No problem, mate

**Comment by Kenan2000** [comment]
Good luck to you too hopefully as well
